from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Tuple, TypedDict

import pandas as pd
from rapidfuzz import fuzz

from .cleaners import parse_datetime_to_iso
from .schemas import (
    CanonicalBankRow,
    CanonicalMerchantRow,
    CanonicalRazorpayRow,
    MatchedLedgerRazorpay,
    MatchedSettlementBank,
    UnresolvedRecord,
)


class Stage3Handoff(TypedDict):
    """
    Structured Stage 2 -> Stage 3 handoff.

    The original Stage 1 unresolved record is preserved unchanged.
    `review_evidence` is trusted deterministic evidence generated by
    Stage 2. Stage 3 must use it directly and must not recompute candidate
    selection through an exact lookup.
    """

    record: UnresolvedRecord
    status: Literal["POTENTIAL_FUZZY_MATCH", "EXCEPTION"]
    score: float
    amount_diff_paise: int
    date_diff_days: Optional[int]
    error_code: Optional[str]
    failed_gates: List[str]
    reason: str
    source_record_id: Optional[str]
    candidate_record_id: Optional[str]
    review_evidence: Dict[str, Any]


# Stage 2 thresholds
ORDER_ID_SIMILARITY_THRESHOLD_AUTO = 0.85
ORDER_ID_SIMILARITY_THRESHOLD_FLOOR = 0.75

UTR_SIMILARITY_THRESHOLD_AUTO = 0.85
UTR_SIMILARITY_THRESHOLD_FLOOR = 0.75

AMOUNT_TOLERANCE_PAISE = 500
MAX_DATE_OFFSET_DAYS = 3


def _date_difference_days(
    first_date: Optional[str],
    second_date: Optional[str],
) -> Optional[int]:
    """
    Parse both dates through cleaners.py and calculate second - first
    in complete calendar days.

    Returns None if either date is missing or cannot be parsed.
    """
    first_iso = parse_datetime_to_iso(first_date)
    second_iso = parse_datetime_to_iso(second_date)

    if not first_iso or not second_iso:
        return None

    try:
        first_datetime = datetime.fromisoformat(first_iso)
        second_datetime = datetime.fromisoformat(second_iso)
    except (ValueError, TypeError):
        return None

    return (second_datetime - first_datetime).days


def _get_failed_gates(
    score: float,
    auto_threshold: float,
    floor_threshold: float,
    amount_diff_paise: int,
    date_diff_days: Optional[int],
) -> List[str]:
    """
    Return failed Stage 2 gates in finance-review priority order.

    Order:
    1. AMOUNT_MISMATCH
    2. DATE_OFFSET_EXCEEDED
    3. LOW_FUZZY_SCORE
    4. BELOW_AUTO_MATCH_THRESHOLD
    """
    failed_gates: List[str] = []

    if amount_diff_paise > AMOUNT_TOLERANCE_PAISE:
        failed_gates.append("AMOUNT_MISMATCH")

    if (
        date_diff_days is not None
        and abs(date_diff_days) > MAX_DATE_OFFSET_DAYS
    ):
        failed_gates.append("DATE_OFFSET_EXCEEDED")

    if score < floor_threshold:
        failed_gates.append("LOW_FUZZY_SCORE")
    elif score < auto_threshold:
        failed_gates.append("BELOW_AUTO_MATCH_THRESHOLD")

    return failed_gates


def _build_other_review_evidence(
    record: UnresolvedRecord,
) -> Dict[str, Any]:
    """
    Build safe evidence for an exception where Stage 2 has no viable
    selected candidate row.
    """
    source_record: Dict[str, Any] = {
        "record_id": record.record_id,
        "source": record.source,
    }

    if record.source == "ledger":
        source_record["gateway_order_id"] = record.context.get(
            "gateway_order_id"
        )
        comparison_type = "LEDGER_TO_RAZORPAY"
        comparison_field = "merchant.gateway_order_id ↔ razorpay.order_id"
        exception_id = f"EXC-LEDGER-{record.record_id}"
        review_lookup = {
            "merchant_csv_search": record.context.get("gateway_order_id"),
            "razorpay_csv_search": record.context.get("gateway_order_id"),
            "bank_csv_search": None,
        }
    elif record.source == "razorpay":
        source_record["settlement_id"] = record.record_id
        source_record["settlement_utr"] = record.context.get(
            "settlement_utr"
        )
        comparison_type = "SETTLEMENT_TO_BANK"
        comparison_field = "razorpay.settlement_utr ↔ bank.utr"
        exception_id = f"EXC-SETTLEMENT-{record.record_id}"
        review_lookup = {
            "merchant_csv_search": None,
            "razorpay_csv_search": record.record_id,
            "bank_csv_search": record.context.get("settlement_utr"),
        }
    else:
        comparison_type = "UNKNOWN"
        comparison_field = "unknown"
        exception_id = f"EXC-{record.source.upper()}-{record.record_id}"
        review_lookup = {
            "merchant_csv_search": None,
            "razorpay_csv_search": None,
            "bank_csv_search": None,
        }

    return {
        "exception_id": exception_id,
        "comparison_type": comparison_type,
        "comparison_field": comparison_field,
        "source_record": source_record,
        "candidate_record": {},
        "comparison": {
            "similarity_score": 0.0,
            "amount_diff_paise": 0,
            "date_diff_days": None,
            "failed_gates": ["OTHER"],
        },
        "review_lookup": review_lookup,
    }


def _other_exception_handoff(
    record: UnresolvedRecord,
    reason: str,
) -> Stage3Handoff:
    """
    Build a consistent handoff when Stage 2 cannot evaluate a real
    candidate score, amount difference, or date difference.
    """
    return {
        "record": record,
        "status": "EXCEPTION",
        "score": 0.0,
        "amount_diff_paise": 0,
        "date_diff_days": None,
        "error_code": "OTHER",
        "failed_gates": ["OTHER"],
        "reason": reason,
        "source_record_id": record.record_id,
        "candidate_record_id": None,
        "review_evidence": _build_other_review_evidence(record),
    }


def _build_candidate_handoff(
    record: UnresolvedRecord,
    score: float,
    amount_diff_paise: int,
    date_diff_days: Optional[int],
    auto_threshold: float,
    floor_threshold: float,
    candidate_label: str,
    source_record_id: Optional[str],
    candidate_record_id: Optional[str],
    review_evidence: Dict[str, Any],
) -> Stage3Handoff:
    """
    Build a Stage 3 handoff after Stage 2 evaluated a specific candidate.

    The selected candidate and all deterministic comparison evidence are
    included in the handoff. Stage 3 must not choose or reconstruct a
    different candidate.
    """
    failed_gates = _get_failed_gates(
        score=score,
        auto_threshold=auto_threshold,
        floor_threshold=floor_threshold,
        amount_diff_paise=amount_diff_paise,
        date_diff_days=date_diff_days,
    )

    review_evidence["comparison"] = {
        "similarity_score": score,
        "amount_diff_paise": amount_diff_paise,
        "date_diff_days": date_diff_days,
        "failed_gates": failed_gates,
    }

    is_potential_match = (
        floor_threshold <= score < auto_threshold
        and amount_diff_paise <= AMOUNT_TOLERANCE_PAISE
        and (
            date_diff_days is None
            or abs(date_diff_days) <= MAX_DATE_OFFSET_DAYS
        )
    )

    if is_potential_match:
        return {
            "record": record,
            "status": "POTENTIAL_FUZZY_MATCH",
            "score": score,
            "amount_diff_paise": amount_diff_paise,
            "date_diff_days": date_diff_days,
            "error_code": None,
            "failed_gates": failed_gates,
            "reason": (
                f"{candidate_label} candidate satisfies amount and date "
                "gates but is below the fuzzy auto-match threshold."
            ),
            "source_record_id": source_record_id,
            "candidate_record_id": candidate_record_id,
            "review_evidence": review_evidence,
        }

    primary_error_code = failed_gates[0] if failed_gates else "OTHER"

    return {
        "record": record,
        "status": "EXCEPTION",
        "score": score,
        "amount_diff_paise": amount_diff_paise,
        "date_diff_days": date_diff_days,
        "error_code": primary_error_code,
        "failed_gates": failed_gates or ["OTHER"],
        "reason": (
            f"{candidate_label} candidate failed one or more Stage 2 "
            "reconciliation gates."
        ),
        "source_record_id": source_record_id,
        "candidate_record_id": candidate_record_id,
        "review_evidence": review_evidence,
    }


def _build_ledger_review_evidence(
    record: UnresolvedRecord,
    merchant_row: CanonicalMerchantRow,
    razorpay_row: CanonicalRazorpayRow,
) -> Dict[str, Any]:
    """
    Build trusted ledger-to-Razorpay evidence for a selected fuzzy candidate.
    """
    gateway_order_id = merchant_row.gateway_order_id
    razorpay_order_id = razorpay_row.order_id

    return {
        "exception_id": f"EXC-LEDGER-{record.record_id}",
        "comparison_type": "LEDGER_TO_RAZORPAY",
        "comparison_field": "merchant.gateway_order_id ↔ razorpay.order_id",
        "source_record": {
            "merchant_order_id": merchant_row.merchant_order_id,
            "gateway_order_id": gateway_order_id,
            "gross_amount_paise": merchant_row.gross_amount_paise,
            "order_created_at": merchant_row.order_created_at,
        },
        "candidate_record": {
            "razorpay_entity_id": razorpay_row.entity_id,
            "razorpay_order_id": razorpay_order_id,
            "razorpay_amount_paise": razorpay_row.amount_paise,
            "payment_captured_at": razorpay_row.payment_captured_at,
            "settlement_id": razorpay_row.settlement_id,
            "settlement_utr": razorpay_row.settlement_utr,
        },
        "comparison": {},
        "review_lookup": {
            "merchant_csv_search": (
                merchant_row.merchant_order_id or gateway_order_id
            ),
            "razorpay_csv_search": (
                razorpay_row.entity_id or razorpay_order_id
            ),
            "bank_csv_search": None,
        },
    }


def _build_settlement_review_evidence(
    record: UnresolvedRecord,
    settlement: Dict[str, Any],
    bank_row: CanonicalBankRow,
    bank_row_index: int,
) -> Dict[str, Any]:
    """
    Build trusted settlement-to-bank evidence for a selected fuzzy bank row.

    `bank_row_index` is the canonical list index and is stable for the
    request. It allows the reviewer UI to identify the exact uploaded
    bank row selected by Stage 2.
    """
    settlement_id = settlement.get("settlement_id") or record.record_id
    settlement_utr = settlement.get("settlement_utr") or record.context.get(
        "settlement_utr"
    )
    bank_reference = bank_row.utr or bank_row.reference_number

    return {
        "exception_id": f"EXC-SETTLEMENT-{settlement_id}",
        "comparison_type": "SETTLEMENT_TO_BANK",
        "comparison_field": "razorpay.settlement_utr ↔ bank.utr",
        "source_record": {
            "settlement_id": settlement_id,
            "settlement_utr": settlement_utr,
            "expected_net_paise": settlement.get("expected_net_paise"),
            "settled_at": settlement.get("settled_at"),
        },
        "candidate_record": {
            "bank_row_index": bank_row_index,
            "bank_reference_number": bank_reference,
            "bank_utr": bank_row.utr,
            "bank_credit_paise": bank_row.credit_paise,
            "bank_transaction_date": bank_row.transaction_date,
            "bank_value_date": bank_row.value_date,
        },
        "comparison": {},
        "review_lookup": {
            "merchant_csv_search": None,
            "razorpay_csv_search": settlement_id,
            "bank_csv_search": bank_reference,
        },
    }


def fuzzy_match_order_id(
    unresolved_ledger: List[UnresolvedRecord],
    merchant_rows: List[CanonicalMerchantRow],
    razorpay_rows: List[CanonicalRazorpayRow],
) -> Tuple[List[MatchedLedgerRazorpay], List[Stage3Handoff]]:
    """
    Evaluate Stage 1 unresolved ledger records against Razorpay order IDs.

    Auto-match only when:
    - order-ID similarity >= 0.85;
    - amount difference <= 500 paise; and
    - date offset <= 3 days when both dates exist.

    For every record not auto-matched, Stage 2 preserves the selected
    Razorpay candidate and its deterministic comparison evidence for Stage 3.
    """
    new_matches: List[MatchedLedgerRazorpay] = []
    stage3_handoffs: List[Stage3Handoff] = []

    merchant_by_gateway_id: Dict[str, CanonicalMerchantRow] = {
        row.gateway_order_id: row
        for row in merchant_rows
        if row.gateway_order_id
    }

    razorpay_by_order_id: Dict[str, List[CanonicalRazorpayRow]] = {}
    for row in razorpay_rows:
        if row.order_id:
            razorpay_by_order_id.setdefault(row.order_id, []).append(row)

    for record in unresolved_ledger:
        if record.source != "ledger":
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "Expected a ledger unresolved record for order-ID matching.",
                )
            )
            continue

        gateway_order_id = record.context.get("gateway_order_id")
        if not gateway_order_id:
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "Missing gateway_order_id in the Stage 1 unresolved context.",
                )
            )
            continue

        merchant_row = merchant_by_gateway_id.get(gateway_order_id)
        if merchant_row is None:
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "No canonical merchant row was found for gateway_order_id.",
                )
            )
            continue

        best_candidate: Optional[CanonicalRazorpayRow] = None
        best_score = 0.0

        for razorpay_order_id, candidates in razorpay_by_order_id.items():
            score = (
                fuzz.ratio(
                    gateway_order_id.upper(),
                    razorpay_order_id.upper(),
                )
                / 100.0
            )

            if score > best_score:
                best_score = score
                best_candidate = candidates[0]

        if best_candidate is None:
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "No Razorpay order-ID candidate was available for fuzzy matching.",
                )
            )
            continue

        amount_diff_paise = abs(
            merchant_row.gross_amount_paise - best_candidate.amount_paise
        )

        date_diff_days = _date_difference_days(
            merchant_row.order_created_at,
            best_candidate.payment_captured_at,
        )

        is_auto_match = (
            best_score >= ORDER_ID_SIMILARITY_THRESHOLD_AUTO
            and amount_diff_paise <= AMOUNT_TOLERANCE_PAISE
            and (
                date_diff_days is None
                or abs(date_diff_days) <= MAX_DATE_OFFSET_DAYS
            )
        )

        if is_auto_match:
            new_matches.append(
                MatchedLedgerRazorpay(
                    merchant_order_id=merchant_row.merchant_order_id,
                    gateway_order_id=gateway_order_id,
                    amount_paise=merchant_row.gross_amount_paise,
                    match_method="FUZZY_ORDER_ID",
                    razorpay_entity_id=best_candidate.entity_id,
                    razorpay_settlement_id=best_candidate.settlement_id,
                )
            )
            continue

        review_evidence = _build_ledger_review_evidence(
            record=record,
            merchant_row=merchant_row,
            razorpay_row=best_candidate,
        )

        stage3_handoffs.append(
            _build_candidate_handoff(
                record=record,
                score=best_score,
                amount_diff_paise=amount_diff_paise,
                date_diff_days=date_diff_days,
                auto_threshold=ORDER_ID_SIMILARITY_THRESHOLD_AUTO,
                floor_threshold=ORDER_ID_SIMILARITY_THRESHOLD_FLOOR,
                candidate_label="Order-ID",
                source_record_id=(
                    merchant_row.merchant_order_id or gateway_order_id
                ),
                candidate_record_id=(
                    best_candidate.entity_id or best_candidate.order_id
                ),
                review_evidence=review_evidence,
            )
        )

    return new_matches, stage3_handoffs


def fuzzy_match_settlement_utr(
    unresolved_settlements: List[UnresolvedRecord],
    settlement_agg: List[Dict[str, Any]],
    bank_rows: List[CanonicalBankRow],
) -> Tuple[List[MatchedSettlementBank], List[Stage3Handoff]]:
    """
    Evaluate Stage 1 unresolved settlements against bank UTRs/narrations.

    Each settlement UTR is compared to:
    - canonical bank.utr, if present;
    - bank.description as a fallback for truncated/messy narration.

    For every record not auto-matched, Stage 2 preserves the exact selected
    bank candidate and its canonical row index in the Stage 3 handoff.
    """
    new_matches: List[MatchedSettlementBank] = []
    stage3_handoffs: List[Stage3Handoff] = []

    settlement_by_id: Dict[str, Dict[str, Any]] = {
        settlement["settlement_id"]: settlement
        for settlement in settlement_agg
        if settlement.get("settlement_id")
    }

    for record in unresolved_settlements:
        if record.source != "razorpay":
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "Expected a Razorpay unresolved record for UTR matching.",
                )
            )
            continue

        settlement_id = record.record_id
        settlement = settlement_by_id.get(settlement_id)

        if settlement is None:
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "No settlement aggregate was found for the unresolved settlement.",
                )
            )
            continue

        settlement_utr = settlement.get("settlement_utr") or record.context.get(
            "settlement_utr"
        )
        expected_net_paise = settlement.get("expected_net_paise")
        settled_at = settlement.get("settled_at")

        if not settlement_utr or expected_net_paise is None:
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "Missing settlement UTR or expected net amount.",
                )
            )
            continue

        best_bank: Optional[CanonicalBankRow] = None
        best_bank_index: Optional[int] = None
        best_score = 0.0

        for bank_row_index, bank_row in enumerate(bank_rows):
            # A settlement payout should correspond to a bank credit,
            # not a debit transaction.
            if bank_row.debit_paise != 0:
                continue

            candidate_texts = [
                text
                for text in [bank_row.utr, bank_row.description]
                if text
            ]

            for candidate_text in candidate_texts:
                score = (
                    fuzz.ratio(
                        settlement_utr.upper(),
                        candidate_text.upper(),
                    )
                    / 100.0
                )

                if score > best_score:
                    best_score = score
                    best_bank = bank_row
                    best_bank_index = bank_row_index

        if best_bank is None or best_bank_index is None:
            stage3_handoffs.append(
                _other_exception_handoff(
                    record,
                    "No bank credit candidate was available for fuzzy UTR matching.",
                )
            )
            continue

        amount_diff_paise = abs(
            int(expected_net_paise) - best_bank.credit_paise
        )

        date_diff_days = _date_difference_days(
            settled_at,
            best_bank.transaction_date,
        )

        is_auto_match = (
            best_score >= UTR_SIMILARITY_THRESHOLD_AUTO
            and amount_diff_paise <= AMOUNT_TOLERANCE_PAISE
            and (
                date_diff_days is None
                or abs(date_diff_days) <= MAX_DATE_OFFSET_DAYS
            )
        )

        if is_auto_match:
            new_matches.append(
                MatchedSettlementBank(
                    settlement_id=settlement_id,
                    settlement_utr=settlement_utr,
                    expected_net_paise=int(expected_net_paise),
                    bank_credit_paise=best_bank.credit_paise,
                    bank_reference=best_bank.utr or best_bank.reference_number,
                    match_method="FUZZY_UTR",
                )
            )
            continue

        review_evidence = _build_settlement_review_evidence(
            record=record,
            settlement=settlement,
            bank_row=best_bank,
            bank_row_index=best_bank_index,
        )

        stage3_handoffs.append(
            _build_candidate_handoff(
                record=record,
                score=best_score,
                amount_diff_paise=amount_diff_paise,
                date_diff_days=date_diff_days,
                auto_threshold=UTR_SIMILARITY_THRESHOLD_AUTO,
                floor_threshold=UTR_SIMILARITY_THRESHOLD_FLOOR,
                candidate_label="UTR",
                source_record_id=settlement_id,
                candidate_record_id=(
                    best_bank.utr or best_bank.reference_number
                ),
                review_evidence=review_evidence,
            )
        )

    return new_matches, stage3_handoffs


def reconcile_fuzzy(
    merchant_rows: List[CanonicalMerchantRow],
    razorpay_rows: List[CanonicalRazorpayRow],
    bank_rows: List[CanonicalBankRow],
    unresolved_from_stage1: List[UnresolvedRecord],
) -> Tuple[
    List[MatchedLedgerRazorpay],
    List[MatchedSettlementBank],
    List[Stage3Handoff],
]:
    """
    Run Stage 2 fuzzy matching only on Stage 1 unresolved records.

    Returns:
    - fuzzy ledger <-> Razorpay matches;
    - fuzzy settlement <-> bank matches;
    - audited Stage 3 handoffs for every record not auto-accepted.
    """
    unresolved_ledger = [
        record
        for record in unresolved_from_stage1
        if record.source == "ledger"
    ]
    unresolved_settlements = [
        record
        for record in unresolved_from_stage1
        if record.source == "razorpay"
    ]

    fuzzy_ledger_matches, stage3_from_ledger = fuzzy_match_order_id(
        unresolved_ledger=unresolved_ledger,
        merchant_rows=merchant_rows,
        razorpay_rows=razorpay_rows,
    )

    razorpay_df = pd.DataFrame(
        [row.model_dump() for row in razorpay_rows]
    )

    if razorpay_df.empty:
        settlement_agg: List[Dict[str, Any]] = []
    else:
        grouped = (
            razorpay_df.groupby("settlement_id", dropna=True)
            .agg(
                gross_sum_paise=("amount_paise", "sum"),
                fee_sum_paise=("fee_paise", "sum"),
                tax_sum_paise=("tax_paise", "sum"),
                settlement_utr=("settlement_utr", "first"),
                settled_at=("settled_at", "first"),
            )
            .reset_index()
        )

        grouped["expected_net_paise"] = (
            grouped["gross_sum_paise"]
            - grouped["fee_sum_paise"]
            - grouped["tax_sum_paise"]
        )

        settlement_agg = grouped.to_dict(orient="records")

    fuzzy_settlement_matches, stage3_from_settlement = (
        fuzzy_match_settlement_utr(
            unresolved_settlements=unresolved_settlements,
            settlement_agg=settlement_agg,
            bank_rows=bank_rows,
        )
    )

    return (
        fuzzy_ledger_matches,
        fuzzy_settlement_matches,
        stage3_from_ledger + stage3_from_settlement,
    )